apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  remoteWrite:
    - url: "http://thanos-receive.monitoring:19291/api/v1/receive"
  resources:
    requests:
      memory: 400Mi
