apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-config
  namespace: monitoring
data:
  config.yaml: |
    type: S3
    config:
      bucket: "your-s3-bucket-name"
      endpoint: "s3.amazonaws.com"
      access_key: "your-access-key"
      secret_key: "your-secret-key"
      insecure: false
