apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: thanos-query
  type: LoadBalancer
