apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
        - name: thanos-query
          image: thanosio/thanos:v0.31.0
          args:
            - query
            - --http-address=0.0.0.0:9090
            - --store=thanos-receiver.monitoring:10902
          ports:
            - containerPort: 9090
