apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
        - name: thanos-store
          image: thanosio/thanos:v0.31.0
          args:
            - store
            - --data-dir=/var/thanos/store
            - --objstore.config-file=/etc/thanos/config.yaml
          ports:
            - containerPort: 10901
          volumeMounts:
            - name: thanos-data
              mountPath: /var/thanos/store
            - name: thanos-config
              mountPath: /etc/thanos
      volumes:
        - name: thanos-data
          emptyDir: {}
        - name: thanos-config
          configMap:
            name: thanos-config
